"""Pydantic contracts for the digest pipeline.

Import from this package, not from its submodules. Everything listed in
`__all__` is the public API that later issues build on.
"""

from ._base import (
    ArticleId,
    ContentHash,
    ContractModel,
    HttpUrlStr,
    InvalidTransitionError,
    NonBlankStr,
    SourceId,
    compute_content_hash,
)
from .articles import (
    BodySource,
    CollectedItem,
    NormalizedArticle,
    ProcessedRecord,
    ProcessedState,
    SourceFetchResult,
    SourceFetchStatus,
    SourceKind,
    SourceMetrics,
)
from .errors import ERROR_DETAIL_MAX_CHARS, ErrorKind, ErrorRecord, ValidationIssue
from .gates import GATE_ORDER, GATE_REASONS, GateExclusionReason, GateName, GateOutcome, GateResult
from .judge import (
    BOUNDARY_EXCLUDED_AUDIT_MAX,
    SOURCE_EVIDENCE_MAX_CHARS,
    AuditCategory,
    AuditTargetKind,
    Confidence,
    FindingAssessment,
    FindingMetrics,
    ImprovementCandidate,
    JudgeFinding,
    JudgeReport,
    Severity,
)
from .metrics import (
    ALLOWED_RUN_TRANSITIONS,
    ALLOWED_STAGE_TRANSITIONS,
    ArticleMetrics,
    AttemptStatus,
    CostBasis,
    CostRecord,
    LLMAttempt,
    LLMCallMetrics,
    LLMRole,
    RunMetrics,
    RunStatus,
    StageMetrics,
    StageName,
    StageStatus,
    TokenUsage,
)
from .selection import (
    MUST_READ_MAX,
    WORTH_KNOWING_MAX,
    AxisScores,
    CaveatStatement,
    Decision,
    DigestEntry,
    DuplicateGroup,
    EvidenceRef,
    ExcludedArticle,
    FactStatement,
    IncludedArticle,
    SelectorOutput,
    Tier,
)

__all__ = [
    "ALLOWED_RUN_TRANSITIONS",
    "ALLOWED_STAGE_TRANSITIONS",
    "BOUNDARY_EXCLUDED_AUDIT_MAX",
    "ERROR_DETAIL_MAX_CHARS",
    "GATE_ORDER",
    "GATE_REASONS",
    "MUST_READ_MAX",
    "SOURCE_EVIDENCE_MAX_CHARS",
    "WORTH_KNOWING_MAX",
    "ArticleId",
    "ArticleMetrics",
    "AttemptStatus",
    "AuditCategory",
    "AuditTargetKind",
    "AxisScores",
    "BodySource",
    "CaveatStatement",
    "CollectedItem",
    "Confidence",
    "ContentHash",
    "ContractModel",
    "CostBasis",
    "CostRecord",
    "Decision",
    "DigestEntry",
    "DuplicateGroup",
    "ErrorKind",
    "ErrorRecord",
    "EvidenceRef",
    "ExcludedArticle",
    "FactStatement",
    "FindingAssessment",
    "FindingMetrics",
    "GateExclusionReason",
    "GateName",
    "GateOutcome",
    "GateResult",
    "HttpUrlStr",
    "ImprovementCandidate",
    "IncludedArticle",
    "InvalidTransitionError",
    "JudgeFinding",
    "JudgeReport",
    "LLMAttempt",
    "LLMCallMetrics",
    "LLMRole",
    "NonBlankStr",
    "NormalizedArticle",
    "ProcessedRecord",
    "ProcessedState",
    "RunMetrics",
    "RunStatus",
    "SelectorOutput",
    "Severity",
    "SourceFetchResult",
    "SourceFetchStatus",
    "SourceId",
    "SourceKind",
    "SourceMetrics",
    "StageMetrics",
    "StageName",
    "StageStatus",
    "Tier",
    "TokenUsage",
    "ValidationIssue",
    "compute_content_hash",
]
