"""Pydantic contracts for the digest pipeline.

Import from this package, not from its submodules. Everything listed in
`__all__` is the public API that later issues build on.
"""

from agent_daily_digest.contracts.base import ArticleId, ContentHash, ContractModel, HttpUrlStr, InvalidTransitionError, NonBlankStr, SourceId, compute_content_hash
from agent_daily_digest.contracts.articles import BodySource, CollectedItem, NormalizedArticle, ProcessedRecord, ProcessedState, SourceFetchResult, SourceFetchStatus, SourceKind, SourceMetrics
from agent_daily_digest.contracts.base import ERROR_DETAIL_MAX_CHARS, ErrorKind, ErrorRecord, ValidationIssue
from agent_daily_digest.contracts.articles import GATE_ORDER, GATE_REASONS, GateExclusionReason, GateName, GateOutcome, GateResult
from agent_daily_digest.contracts.editorial import BOUNDARY_EXCLUDED_AUDIT_MAX, SOURCE_EVIDENCE_MAX_CHARS, AuditCategory, AuditTargetKind, Confidence, FindingAssessment, FindingMetrics, ImprovementCandidate, JudgeFinding, JudgeReport, Severity
from .metrics import (
    ALLOWED_RUN_TRANSITIONS,
    ALLOWED_STAGE_TRANSITIONS,
    ArticleMetrics,
    AttemptStatus,
    CostBasis,
    CostRecord,
    LLMAttempt,
    LLMCallMetrics,
    LLMRole,
    RunMetrics,
    RunStatus,
    StageMetrics,
    StageName,
    StageStatus,
    TokenUsage,
)
from .research import (
    CONCRETE_EVIDENCE_KINDS,
    EVIDENCE_QUOTE_MAX_CHARS,
    REPRODUCIBILITY_EVIDENCE_KINDS,
    Claim,
    ClaimKind,
    Concept,
    ConceptArea,
    DocId,
    Evidence,
    EvidenceId,
    EvidenceKind,
    EvidenceLocation,
    EvidencePacket,
    FetchedReference,
    Limitation,
    Paragraph,
    ParagraphId,
    ResearchBudget,
    ResearchStatus,
    ResearchStopReason,
    ResearchTrace,
    SourceDocument,
    make_evidence_id,
    parse_evidence_id,
)
from agent_daily_digest.contracts.editorial import MUST_READ_MAX, WORTH_KNOWING_MAX, AxisScores, CaveatStatement, Decision, DigestEntry, DuplicateGroup, EvidenceRef, ExcludedArticle, FactStatement, IncludedArticle, SelectorOutput, Tier

__all__ = [
    "ALLOWED_RUN_TRANSITIONS",
    "ALLOWED_STAGE_TRANSITIONS",
    "BOUNDARY_EXCLUDED_AUDIT_MAX",
    "CONCRETE_EVIDENCE_KINDS",
    "ERROR_DETAIL_MAX_CHARS",
    "EVIDENCE_QUOTE_MAX_CHARS",
    "GATE_ORDER",
    "GATE_REASONS",
    "MUST_READ_MAX",
    "REPRODUCIBILITY_EVIDENCE_KINDS",
    "SOURCE_EVIDENCE_MAX_CHARS",
    "WORTH_KNOWING_MAX",
    "ArticleId",
    "ArticleMetrics",
    "AttemptStatus",
    "AuditCategory",
    "AuditTargetKind",
    "AxisScores",
    "BodySource",
    "CaveatStatement",
    "Claim",
    "ClaimKind",
    "CollectedItem",
    "Concept",
    "ConceptArea",
    "Confidence",
    "ContentHash",
    "ContractModel",
    "CostBasis",
    "CostRecord",
    "Decision",
    "DigestEntry",
    "DocId",
    "DuplicateGroup",
    "ErrorKind",
    "ErrorRecord",
    "Evidence",
    "EvidenceId",
    "EvidenceKind",
    "EvidenceLocation",
    "EvidencePacket",
    "EvidenceRef",
    "ExcludedArticle",
    "FactStatement",
    "FetchedReference",
    "FindingAssessment",
    "FindingMetrics",
    "GateExclusionReason",
    "GateName",
    "GateOutcome",
    "GateResult",
    "HttpUrlStr",
    "ImprovementCandidate",
    "IncludedArticle",
    "InvalidTransitionError",
    "JudgeFinding",
    "JudgeReport",
    "LLMAttempt",
    "LLMCallMetrics",
    "LLMRole",
    "Limitation",
    "NonBlankStr",
    "NormalizedArticle",
    "Paragraph",
    "ParagraphId",
    "ProcessedRecord",
    "ProcessedState",
    "ResearchBudget",
    "ResearchStatus",
    "ResearchStopReason",
    "ResearchTrace",
    "RunMetrics",
    "RunStatus",
    "SelectorOutput",
    "Severity",
    "SourceDocument",
    "SourceFetchResult",
    "SourceFetchStatus",
    "SourceId",
    "SourceKind",
    "SourceMetrics",
    "StageMetrics",
    "StageName",
    "StageStatus",
    "Tier",
    "TokenUsage",
    "ValidationIssue",
    "compute_content_hash",
    "make_evidence_id",
    "parse_evidence_id",
]
